const assert=require('node:assert/strict');const E=require('../app/src/main/assets/engine.js');
const h={visibility:[10000],wind_speed_10m:[3],wind_gusts_10m:[5],cloud_cover_low:[0],precipitation:[0],temperature_2m:[5],weather_code:[0],is_day:[1]};
assert.equal(E.assess(h,0).level,0);
assert.equal(E.assess({...h,visibility:[500]},0).level,2);
assert.equal(E.assess({...h,visibility:[1000]},0).level,1);
assert.equal(E.assess({...h,visibility:[3000]},0).level,0);
assert.equal(E.assess({...h,wind_gusts_10m:[25]},0).level,2);
assert.equal(E.assess({...h,weather_code:[95]},0).level,2);
assert.equal(E.assess({...h,weather_code:[66]},0).level,2);
assert.equal(E.assess({...h,weather_code:[71]},0).level,1);
assert.equal(E.assess({...h,visibility:[null]},0).level,3);
assert.equal(E.assess({...h,visibility:[null],wind_gusts_10m:[30]},0).level,2);
assert.equal(E.assess(h,-1).level,3);
assert.equal(E.combine([E.assess(h,0),E.assess({...h,visibility:[null]},0)]).level,3);
assert.equal(E.combine([E.assess({...h,visibility:[500]},0),E.assess({...h,visibility:[null]},0)]).level,2);
const rp=E.routePoints({lat:61.25,lon:73.4},{lat:65,lon:74});assert.equal(rp.points.length,5);assert(rp.distance>400);assert(Math.abs(rp.points[4].lat-65)<1e-9);
const dateline=E.routePoints({lat:60,lon:179},{lat:60,lon:-179});assert(dateline.distance<120);assert(Math.abs(dateline.points[2].lon)>179);
assert.throws(()=>E.routePoints({lat:0,lon:0},{lat:0,lon:180}));
console.log('17 проверок погодной оценки и маршрута пройдены');
