const assert=require('node:assert/strict'),E=require('../app/src/main/assets/engine.js');
const csv='time,station,latitude[unit="degrees_north"],longitude[unit="degrees_east"],Geopotential_height_cloud_ceiling[unit="gpm"],Geopotential_height_surface[unit="gpm"]\n2026-10-07T00:00:00Z,x,61.25,73.5,250,50\n2026-10-07T03:00:00Z,x,61.25,73.5,150,50\n2026-10-07T06:00:00Z,x,61.25,73.5,20000,50\n2026-10-07T09:00:00Z,x,61.25,73.5,NaN,50';
const rows=E.parseCloudCsv(csv),at=s=>Date.parse('2026-10-07T'+s+':00Z');assert.equal(rows.length,4);assert.equal(rows[2].reason,null);assert.equal(rows[2].clear,true);assert.equal(rows[2].rawHeight,20000);assert.equal(rows[3].reason,'missingHeight');assert.equal(E.cloudAt(rows,at('00:00')).value,200);assert(Math.abs(E.cloudAt(rows,at('01:00')).value-166.6666667)<.0001);assert.equal(E.cloudAt(rows,at('03:00')).value,100);assert.equal(E.cloudAt(rows,at('04:00')),null);assert.equal(E.cloudAt(rows,at('06:00')).clear,true);assert.equal(E.cloudAt(rows,at('09:00')),null);assert.equal(E.cloudAt(rows,at('10:00')),null);assert.equal(E.cloudAt(rows,Date.parse('2026-10-06T23:00Z')),null);assert.throws(()=>E.parseCloudCsv('<html>Error</html>'));
const r=E.augment(E.assess({visibility:[10000],wind_speed_10m:[2],wind_gusts_10m:[3],cloud_cover_low:[20],precipitation:[0],temperature_2m:[5],weather_code:[1],is_day:[1],wind_direction_10m:[20]},0),null,at('00:00'),E.defaults,{});const cloud=E.cloudAt(rows,at('03:00')),merged=E.withCloud(r,cloud,E.defaults);assert.equal(merged.level,2);assert.equal(E.weatherIndex([merged],E.defaults),0);assert.equal(r.cloud,null);const combined=E.withCloud({...r,cloud:{known:true,value:70,clear:false}},cloud,E.defaults);assert.equal(combined.cloud.value,70);assert.equal(combined.cloud.source,undefined);assert.equal(E.withCloud({...r,cloud:{known:true,value:null,clear:true}},cloud,E.defaults).cloud.value,null);
const missing=E.withCloud(E.assess({},0),cloud,E.defaults);assert.equal(missing.missing,true);assert.equal(E.weatherIndex([missing],E.defaults),0);assert.equal(E.cloudAt([{ms:at('00:00'),value:200},{ms:at('09:00'),value:100}],at('03:00')),null);console.log('Облака: разбор CSV, поверхность, сроки, интерполяция, пропуски, отсутствие потолка, объединение TAF/GFS — пройдены');

const clear=E.cloudAt(rows,at('06:00'));assert.equal(clear.value,null);
assert.equal(E.withCloud(r,clear,E.defaults).g.cloud,0);
const mixed=E.withCloud({...r,cloud:{known:true,value:70,clear:false}},clear,E.defaults);assert.equal(mixed.cloud.value,70);assert.equal(mixed.cloud.clear,false);
assert.equal(E.withCloud({...r,cloud:{known:true,value:null,clear:true}},clear,E.defaults).cloud.clear,true);
const rr=E.parseCloudCsv(csv.replace('20000,50','19999.902,50'));assert.equal(rr[2].clear,true);
assert.equal(E.cloudAt([{ms:at('00:00'),value:null,clear:true},{ms:at('03:00'),value:null,clear:true}],at('01:00')).clear,true);
assert.equal(E.cloudAt([{ms:at('00:00'),value:null,clear:true},{ms:at('03:00'),value:null,clear:false}],at('01:00')),null);
assert.equal(E.parseCloudCsv(csv.replace('20000,50','19500,50'))[2].clear,false);
console.log('GFS no-ceiling sentinel, packed tolerance, TAF priority, temporal transitions and missing data passed');
