const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('../app/src/main/assets/engine.js'),F=require('../app/src/main/assets/fallback.js');
const point={lat:61.342,lon:73.422},groups=Object.fromEntries(['surface','temp','wind'].map(g=>[g,F.parse(fs.readFileSync(__dirname+'/fixtures/gfs-'+g+'.csv','utf8'),g,point)])),ms=Date.parse('2026-10-07T00:00:00Z');
assert(Math.abs(groups.temp[0].x.temp-.5647)<.0001);assert(Math.abs(groups.surface[0].x.rain-.0288)<.0001);assert(Math.abs(groups.wind[0].x.wind-Math.hypot(1.3599511,-.9655078))<.0001);
const empty=E.assess({},-1),merged=F.merge(empty,groups,ms+3600000,E.defaults);for(const k of ['visibility','temp','wind','gust','rain','direction'])assert(E.valid(merged.x[k]),k);assert.equal(merged.x.code,null);assert.equal(merged.x.day,null);assert.equal(merged.x.low,null);assert.equal(merged.fallbackUsed,true);assert(E.indexDetails([merged],E.defaults).partial);
const primary=E.assess({visibility:[9000],wind_speed_10m:[5]},0),mixed=F.merge(primary,groups,ms,E.defaults);assert.equal(mixed.x.visibility,9000);assert.equal(mixed.x.wind,5);assert.equal(mixed.sources.visibility,'Open-Meteo');assert.equal(mixed.sources.temp,'~ GFS');assert.equal(F.merge(empty,groups,ms-3600000,E.defaults).x.visibility,null);
const series=[{ms,x:{visibility:5000,temp:0,wind:2,direction:350,rain:0}},{ms:ms+3*3600000,x:{visibility:1000,temp:6,wind:5,direction:10,rain:2}}];const sampled=F.sample(series,ms+1.5*3600000);assert.equal(sampled.visibility,1000);assert.equal(sampled.wind,5);assert.equal(sampled.temp,3);assert.equal(sampled.direction,0);assert.equal(sampled.rain,2);assert.deepEqual(F.sample([series[0],{...series[1],ms:ms+6*3600000}],ms+3600000),{});
assert.throws(()=>F.parse(fs.readFileSync(__dirname+'/fixtures/gfs-temp.csv','utf8'),'temp',{lat:0,lon:0}),/40/);assert.throws(()=>F.parse('time,latitude[x],longitude[x]\n2026-10-07T00:00:00Z,61,73','surface',point));
const gustBad=F.parse(fs.readFileSync(__dirname+'/fixtures/gfs-surface.csv','utf8').replace('1493.946,3.3,8.0E-6','1493.946,-2,8.0E-6'),'surface',point);assert.equal(gustBad[0].x.gust,null);
console.log('GFS fallback: real CSV, units, 2m/10m fields, interpolation, bounds, primary priority, missing hazards, physical values passed');
