const {test}=require('node:test'),assert=require('node:assert/strict');global.Engine=require('../app/src/main/assets/engine.js');const S=require('../app/src/main/assets/secondary.js'),E=global.Engine;
const ms=Date.parse('2026-10-07T12:00:00Z'),point={lat:66.3,lon:83.25};
function fixture(){return {geometry:{coordinates:[83.25,66.3]},properties:{meta:{updated_at:new Date().toISOString(),units:{air_temperature:'celsius',wind_speed:'m/s',wind_from_direction:'degrees',cloud_area_fraction_low:'%',precipitation_amount:'mm'}},timeseries:[0,1].map(n=>({time:new Date(ms+n*3600000).toISOString(),data:{instant:{details:{air_temperature:2+n,wind_speed:4+n,wind_from_direction:90,cloud_area_fraction_low:80}},next_1_hours:{details:{precipitation_amount:0},summary:{symbol_code:'partlycloudy_day'}}}}))}};}
test('independent fields fill outage without inventing gust or visibility',()=>{const rows=S.parse(fixture(),point).rows,r=S.merge(E.assess({},-1),rows,ms+1800000,E.defaults);assert.equal(r.x.temp,2.5);assert.equal(r.x.wind,5);assert.equal(r.x.low,80);assert.equal(r.x.rain,0);assert.equal(r.x.code,2);assert.equal(r.x.visibility,null);assert.equal(r.x.gust,null);assert.equal(r.sources.low,'MET Norway');});
test('primary valid values and provenance win',()=>{const primary=E.assess({temperature_2m:[7],weather_code:[95],cloud_cover_low:[12]},0);primary.sources={temp:'Open-Meteo'};const r=S.merge(primary,S.parse(fixture(),point).rows,ms,E.defaults);assert.equal(r.x.temp,7);assert.equal(r.x.code,95);assert.equal(r.x.low,12);assert.equal(r.sources.temp,'Open-Meteo');});
test('missing 1h values are not made from 6h periods; unknown symbols stay unknown',()=>{const f=fixture();for(const row of f.properties.timeseries){row.data.next_6_hours=row.data.next_1_hours;delete row.data.next_1_hours;}const r=S.parse(f,point).rows[0].x;assert.equal(r.code,null);assert.equal(r.rain,null);assert.equal(S.code('new_unknown_symbol'),null);assert.equal(S.code('heavyrainandthunder_night'),95);assert.equal(S.code('lightsleet'),68);assert.equal(S.code('clearsky_day'),0);});
test('bounds, stale issue, mismatched position and incorrect units rejected',()=>{let f=fixture();f.geometry.coordinates=[NaN,66.3];assert.throws(()=>S.parse(f,point),/координаты/);f=fixture();f.geometry.coordinates=[10,10];assert.throws(()=>S.parse(f,point),/координаты/);f=fixture();f.properties.meta.updated_at=new Date(Date.now()-25*3600000).toISOString();assert.throws(()=>S.parse(f,point),/устаревший/);f=fixture();f.properties.meta.units.wind_speed='km/h';assert.equal(S.parse(f,point).rows[0].x.wind,null);});
test('solar day handles equator, polar night and polar day',()=>{assert.equal(S.day(Date.parse('2026-03-20T12:00Z'),{lat:0,lon:0}),1);assert.equal(S.day(Date.parse('2026-03-20T00:00Z'),{lat:0,lon:0}),0);assert.equal(S.day(Date.parse('2026-12-21T12:00Z'),{lat:80,lon:0}),0);assert.equal(S.day(Date.parse('2026-06-21T00:00Z'),{lat:80,lon:0}),1);assert.equal(S.day(ms,{lat:100,lon:0}),null);});
test('no extrapolation or interpolation across missing hours',()=>{const rows=S.parse(fixture(),point).rows;assert.deepEqual(S.sample(rows,ms-1),{});assert.deepEqual(S.sample(rows,ms+3600001),{});rows[1].ms+=3600000;assert.deepEqual(S.sample(rows,ms+1800000),{});});
